name: mobile_ziswaf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  animated_splash_screen: 1.3.0
  pin_code_fields: 7.4.0
  get_cli: 1.8.1
  image_picker: 0.8.6
  percent_indicator: ^4.2.2
  appbar_animated: ^0.0.3
  flutter_slidable: ^2.0.0
  jiffy: 5.0.0
  intl: 0.17.0
  shared_preferences: 2.0.15
  firebase_auth: ^4.1.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.3
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.11.0
  flutter_easyloading: 3.0.5
  flutter:
    sdk: flutter
  currency_text_input_formatter: ^2.1.7
  path: ^1.8.2
  photo_view: ^0.14.0
  mask_text_input_formatter: ^2.4.0
  pdftron_flutter: ^1.0.0-beta.59
  permission_handler: ^8.1.1
  dio: ^4.0.6
  rename: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon-launcer-ziswaf.png"

flutter:
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/img/bank/
  uses-material-design: true
